# Generated by Django 4.2.23 on 2025-07-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_plane_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='plane',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
