# Generated by Django 4.2.23 on 2025-07-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_plane_created_at_alter_plane_updated_at'),
        ('api', '0004_add_schedule'),
    ]

    operations = [
    ]
