# Generated by Django 4.2.23 on 2025-07-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20250709_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='speed',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='plane',
            name='direction',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='plane',
            name='latitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='plane',
            name='longitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
